// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmRRmn3-hwXTWGg_9QQDwneIeNKROSWhA',
    appId: '1:570976278139:android:b136b7953faa3bdc2374de',
    messagingSenderId: '570976278139',
    projectId: 'engagepoint-a2c47',
    storageBucket: 'engagepoint-a2c47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdWNH7vaFnjvyfhGum8aWotxQ5Ago473o',
    appId: '1:570976278139:ios:a02524566c2858162374de',
    messagingSenderId: '570976278139',
    projectId: 'engagepoint-a2c47',
    storageBucket: 'engagepoint-a2c47.firebasestorage.app',
    androidClientId: '570976278139-gbnq7ocseqjiu3akaivn0srsh21ais00.apps.googleusercontent.com',
    iosClientId: '570976278139-3m7ok8amg6r1au9t2e5je94edm3h41mu.apps.googleusercontent.com',
    iosBundleId: 'com.groups11.engagepoint.flutterApp',
  );

}